@host=http://localhost:5000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOjEsInJvbGUiOiJkb2N0b3IiLCJleHAiOjE3MjkzODg1OTd9.VYDSqbqR4CpjGEyEC_tNmBb8nzEQ909CmDRCevJd8lg

### Health Check
GET {{host}}/health
Content-Type: application/json

### Create a Schedule
POST {{host}}/api/v1/schedules
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "date_time_available": "2024-07-22 08:00",
    "active": true
}

### Get Schedules
GET {{host}}/api/v1/schedules
Content-Type: application/json
Authorization: Bearer {{token}}

### Get Schedule by Id
GET {{host}}/api/v1/schedules/2
Content-Type: application/json
Authorization: Bearer {{token}}