apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scheduler-service-hpa
  namespace: ns-scheduler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scheduler-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50