apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: ns-scheduler-service
  labels:
    app: scheduler-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: scheduler-service