@startuml delete_schedule

title Excluir Agenda

actor "User" as user
participant "Schedule Service" as schedule_service
participant "Database" as database

note over user
Neste exemplo, o usuário
deve ser um **médico**.
end note

user -> schedule_service: DELETE /schedules/{scheduleId}\n(Bearer JWT)

activate schedule_service
schedule_service -> schedule_service: Verificar se a agenda não está\nreservada por nenhum paciente
schedule_service -> database: Excluir agenda
database --> schedule_service: Excluído
schedule_service --> user: 204 No Content
deactivate schedule_service

@enduml