@startuml get_schedule

title Obter Agenda

actor "User" as user
participant "Schedule Service" as schedule_service
participant "Database" as database

note over user
Neste exemplo, o usuário
deve ser um **médico**.
end note

user -> schedule_service: GET /schedules/{scheduleId}\n(Bearer JWT)

activate schedule_service
schedule_service -> schedule_service: Verificar se o agendamento existe
schedule_service -> database: Obter agendamento
database --> schedule_service: Agendamento
schedule_service --> user: 200 OK
deactivate schedule_service

@enduml