@startuml get_schedules

title Obter Agendas

actor "User" as user
participant "Schedule Service" as schedule_service
participant "Database" as database

note over user
Neste exemplo, o usuário
deve ser um **médico**.
end note

user -> schedule_service: GET /schedules\n(Bearer JWT)

activate schedule_service
schedule_service -> database: Obter todos os agendamentos
database --> schedule_service: Agendamentos
schedule_service --> user: 200 OK
deactivate schedule_service

@enduml