@startuml get_schedules

title Getting all Schedules Flow

actor "User" as user
participant "Schedule Service" as schedule_service
participant "Database" as database

note over user
    In this example, the user
    must be a **doctor**.
end note

user -> schedule_service: GET /schedules\n(Bearer JWT)

activate schedule_service
schedule_service -> database: Get all schedules
database --> schedule_service: Schedules
schedule_service --> user: 200 OK
deactivate schedule_service

@enduml