@startuml update_schedule

title Atualizar Agenda

actor "User" as user
participant "Schedule Service" as schedule_service
participant "Database" as database

note over user
Neste exemplo, o usuário
deve ser um **médico**.
end note

user -> schedule_service: PUT /schedules\n(Bearer JWT)

activate schedule_service
schedule_service -> schedule_service: Validar detalhes da agenda
schedule_service -> database: Atualizar a agenda
database --> schedule_service: Atualizado
schedule_service --> user: 200 OK
deactivate schedule_service

@enduml