@startuml update_schedule

title Update a Schedule Flow

actor "User" as user
participant "Schedule Service" as schedule_service
participant "Database" as database

note over user
In this example, the user
must be a **doctor**.
end note

user -> schedule_service: PUT /schedules\n(Bearer JWT)

activate schedule_service
schedule_service -> schedule_service: Validate schedule details
schedule_service -> database: Update schedule
database --> schedule_service: Updated
schedule_service --> user: 200 OK
deactivate schedule_service

@enduml